# Generated by Django 5.1.2 on 2024-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0004_alter_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
