# Generated by Django 5.1.2 on 2024-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0005_alter_room_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo_image', models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='logo_image')),
            ],
        ),
    ]
