# Generated by Django 5.1.2 on 2024-10-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0006_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
