# Generated by Django 5.1.2 on 2024-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0007_alter_siteasset_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image1',
            field=models.FileField(blank='True', default='no_image/noimage.png', null=True, upload_to='room_images/'),
        ),
    ]
