# Generated by Django 5.1.2 on 2024-10-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0007_alter_siteasset_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAsset',
        ),
    ]
