# Generated by Django 5.1.2 on 2024-10-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0008_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
