# Generated by Django 5.1.2 on 2024-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0009_delete_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='interior_image',
            new_name='hotel_image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_view',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_view',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_image'),
        ),
    ]
