# Generated by Django 5.1.2 on 2024-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0010_rename_interior_image_hotel_hotel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_view',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_banner',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_banner'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_view',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_view'),
        ),
    ]
