# Generated by Django 5.1.2 on 2024-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0011_remove_hotel_room_view_alter_hotel_hotel_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_view',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='room_view'),
        ),
    ]
