# Generated by Django 5.1.2 on 2024-10-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0012_hotel_room_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_view',
            new_name='hotel_view1',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_view2',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_view'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_view3',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_view'),
        ),
    ]
