# Generated by Django 5.1.2 on 2024-10-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0013_rename_hotel_view_hotel_hotel_view1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_view1',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_view1'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_view2',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_view2'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_view3',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_view3'),
        ),
    ]
