# Generated by Django 5.1.2 on 2024-10-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0014_alter_hotel_hotel_view1_alter_hotel_hotel_view2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_image',
            new_name='room_image1',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image2',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image3',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_room'),
        ),
    ]
