# Generated by Django 5.1.2 on 2024-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0015_rename_room_image_room_room_image1_room_room_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image2',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='room_image2'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image3',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='room_image3'),
        ),
    ]
